<?php

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$titleHtml = '';
if (trim($block->getPageHeading())) {
    $titleHtml = '<span class="base" data-ui-id="page-title-wrapper" '
        . $block->getAddBaseAttribute()
        . '>'
        . $block->escapeHtml($block->getPageHeading())
        . '</span>';
}
?>

<?php if ($titleHtml) : ?>
<div class="page-title-wrapper<?= $block->escapeHtmlAttr($cssClass) ?>">
    <h1 class="page-title"
        <?php if ($block->getId()) : ?> id="<?= $block->escapeHtmlAttr($block->getId()) ?>" <?php endif; ?>
        <?php if ($block->getAddBaseAttributeAria()) : ?>
            aria-labelledby="<?= $block->escapeHtmlAttr($block->getAddBaseAttributeAria()) ?>"
        <?php endif; ?>>
        <?= /* @noEscape */ $titleHtml ?>
    </h1>
    <h2 class="page-title"><?= $block->escapeHtml(__('Lorem ipsum bla-bla-bla')) ?>    <?= $block->getChildHtml() ?></h2>
    <h4 class="page-title"><?= $block->escapeHtml(__('alb-alb-alb Lorem ipsum ')) ?>    <?= $block->getChildHtml() ?></h4>

    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam quidem totam cupiditate eligendi cum distinctio corporis, mollitia natus impedit expedita reprehenderit vero eaque adipisci maiores accusantium fugit inventore! At ab, ex possimus nemo harum sapiente officia quaerat similique quod, dolorem velit labore adipisci. Aliquam mollitia perspiciatis consequatur beatae incidunt maxime, recusandae distinctio amet perferendis! Fugit dolorum aut ducimus eos ex neque quis repellat tenetur quibusdam minima placeat cum accusamus quos obcaecati quas ipsam, inventore earum, repellendus ullam et unde. Eos architecto quidem minus esse animi. Magni unde beatae doloribus porro quas exercitationem neque consequuntur maiores officia, harum sequi sit repellendus.</p>

</div>
<?php endif; ?>
